# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMAqkBzDtz417cBKiLz2xd-pT-C0g2lm
"""

!pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# import requests
# import io
# 
# # Streamlit app title and introduction
# st.title("Car Evaluation Dataset")
# st.header("""Data information""")
# st.text("""
# Derived from a simple hierarchical decision model, this dataset may be useful for testing constructive induction and structure discovery methods:
# - **buying**: vhigh, high, med, low.
# - **maint**: vhigh, high, med, low.
# - **doors**: 2, 3, 4, 5.
# - **persons**: 2, 4, 5.
# - **lug_boot**: small, med, big.
# - **safety**: low, med, high.
# - **class**: unacc, acc, good, vgood
# """)
# 
# # Function to fetch and read CSV from Google Drive
# @st.cache_data
# def load_data_from_google_drive(file_url):
#     file_id = file_url.split('/')[-2]
#     dwn_url = f'https://drive.google.com/uc?export=download&id={file_id}'
#     response = requests.get(dwn_url)
#     data = pd.read_csv(io.StringIO(response.text))
#     return data
# 
# # Enter the Google Drive link of your CSV file here
# google_drive_link = st.text_input("Enter Google Drive link of the CSV file:", "")
# 
# if google_drive_link:
#     try:
#         # Load the dataset
#         data = load_data_from_google_drive(google_drive_link)
# 
#         # Capture the output of data.info() into a string buffer
#         buffer = io.StringIO()
#         data.info(buf=buffer)
#         s = buffer.getvalue()
# 
#         # Display the info as text in Streamlit
#         st.text(s)
#         st.text("""
# Analysis:
# **Missing Data**: There are no missing values in any of the columns, as indicated by the non-null count matching the total number of entries (1727) for each column.
# **Data Types**: The categorical variables are represented as object type.
# **Memory Usage**: The dataset uses 94.6 KB of memory, which is manageable for most analyses.
# **Overall**: The dataset is clean with no missing values, and the data types are relatively appropriate for the categorical nature of the variables. However, the columns should be renamed for clarity would be beneficial and the datatypes of doors and persons should be changed to facilitate subsequent analysis.""")
# 
#         # Rename columns
#         data.columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
# 
#         st.header("""Data size and dimension""")
# 
#         # Display the dataset's shape
#         st.write(f"Dataset shape: {data.shape}")
# 
#         # Display the first few rows of the dataset
#         st.dataframe(data.head())
#         st.text("""
# This dataset consists of 1727 rows and 7 columns. Each row represents a unique car evaluation, and each column corresponds to a specific attribute or feature of the car. The columns include:
# - **buying**: Buying price of the car (Categorical)
# - **maint**: Maintenance price of the car (Categorical)
# - **doors**: Number of doors in the car (Numerical)
# - **persons**: Capacity in terms of persons to carry (Numerical)
# - **lug_boot**: Size of the luggage boot (Categorical)
# - **safety**: Estimated safety of the car (Categorical)
# - **class**: Evaluation level of the car (Target variable, Categorical)
# """)
# 
# 
# 
#         st.header("""Missing Data""")
# 
#         # Identify missing data
#         missing_data = data.isnull().sum()
#         # Streamlit elements for text output
#         st.write("Missing Data Counts:")
#         st.write(missing_data)
# 
#         # Visualize missing data
#         fig, ax = plt.subplots(figsize=(6, 4))
#         sns.heatmap(data.isnull(), cmap='viridis', cbar=False, ax=ax)
#         ax.set_title('Missing Data Visualization')
#         st.pyplot(fig)
# 
#         st.text("""
# - The analysis of missing data in the dataset reveals that there are no missing values across all columns. This is shown by the missing data count table, which shows zero missing values for each column.
# - The heatmap visualization further supports this finding, as it does not display any gaps or missing data points. This also indicates that the dataset is complete and does not require any imputation or handling of missing values.
# """)
# 
#         st.header("""Duplicated Values""")
# 
#         # Identify duplicate data
#         duplicate_rows = data[data.duplicated()]
#         # Display duplicate rows if they exist
#         if not duplicate_rows.empty:
#             st.write("Duplicated Rows:")
#             st.dataframe(duplicate_rows)
#         else:
#             st.write("No duplicated rows found.")
#         # Print the count of duplicate rows
#         st.write(f"Number of Duplicated Rows: {len(duplicate_rows)}")
#         st.text("""
# - The analysis of duplicate data in the dataset indicates that there are no duplicate rows. This is confirmed by the output above, which shows zero duplicated rows.
# """)
#         st.header("""Numerical data columns""")
# 
#         # Basic summary statistics of the dataset
#         st.write("Summary statistics of the numerical columns:")
#         #st.write(data.describe())
# 
#         # Convert and clean up columns
#         data['doors'] = data['doors'].replace('5more', '5')
#         data['doors'] = data['doors'].astype(int)
#         data['persons'] = data['persons'].replace('more', '5')
#         data['persons'] = data['persons'].astype(int)
# 
#         # Generate summary statistics for numerical columns
#         summary_stats = data.describe()
#         st.write(summary_stats)
#         st.text("""
# Analysis:
# - **Numeric Columns**: `doors` and `persons` are the two numeric columns in the dataset.
# - **Unique Values**: At the begining, the unique values in these two columns `doors` and `persons` is in `object` type. Although it still shows the correct number values, these can be detrimental to the following analysis steps. Therefore, the datatype were changed into `int` type.
# - **Central Tendency**: The mean and median values for both `doors` (at 3.5) and `persons` (at 3.67) are close to each other, indicating a relatively symmetric distribution for these columns.
# - **Dispersion**: The standard deviation values indicate the spread of the data around the mean. For `doors`, the standard deviation is 1.118, and for `persons`, it is 1.248. This suggests that the number of doors and persons varies moderately around their respective means.
# - **Range**: The range (difference between the minimum and maximum values) for both columns is 3, indicating a moderate spread of values.
# - **Percentiles**: The percentiles provide insights into the distribution of the data. For `doors`, 25% of the data has 2.75 or fewer doors, 50% has 3.50 or fewer, and 75% has 4.25 or fewer; and for `persons`, 25% of the data can accommodate 2 or fewer persons, 50% can accommodate 4 or fewer, and 75% can accommodate 5 or fewer.
# - **Outliers**: The minimum and maximum values for both columns are within a reasonable range, suggesting that there are no extreme outliers.
# """)
# 
# 
#         st.header("""Categorical data columns""")
# 
#         # Select numeric data
#         numeric_data = data.select_dtypes(include='number').columns
#         #st.write("Numeric Data Columns:")
#         #st.write(numeric_data)
# 
#         # Select categorical data
#         categorical_data = data.select_dtypes(exclude='number').columns
#         st.write("Categorical Data Columns:")
#         st.write(categorical_data)
# 
#         # Display unique values in categorical columns
#         for col in categorical_data:
#             unique_values = data[col].unique()
#             st.write(f"Unique Values in Column '{col}':")
#             st.write(unique_values)
#             # Optionally, display value counts
#             st.write(data[col].value_counts())
#         st.text("""
# Unique Values:
# - buying: ['vhigh', 'high', 'med', 'low']
# - maint: ['vhigh', 'high', 'med', 'low']
# - lug_boot: ['small', 'med', 'big']
# - afety: ['low', 'med', 'high']
# - class: ['unacc', 'acc', 'vgood', 'good']
# Analysis:
# - In `buying`, the values are distributed relatively evenly with each unique value appearing around 432 times.
# - In `maint`, approximately 432 occurrences of each unique value indicate a generally even distribution of the values.
# - In `lug_boot`, each unique value appears around 576 times, indicating a fairly equitable distribution of the values.
# - In `safety`, the values are distributed relatively evenly with each unique value appearing around 576 times.
# - In `class`, the values are distributed unevenly, with "unacc" accounting for 1210 out of 1728 instances.
# Overall:
# - The data of categorical values ​​does not look unusual. Each unique value has complete data and no outliers.
# - Almost the categorical data in this dataset is evenly distributed. However, the values in `class` data are distributed unevenly, this implies that the majority of the cars in the sample are viewed as unsatisfactory.
# """)
# 
# 
#         st.header("""Plotting Distribution and Box Plots for Numeric Columns""")
# 
#         # Plotting Distribution and Box Plots for Numeric Columns
#         for col in numeric_data:
#             fig, axes = plt.subplots(2, 1, figsize=(10, 5))  # 2 rows, 1 column
#             # Distribution Plot (Top Subplot)
#             sns.histplot(data=data, x=col, kde=True, ax=axes[0])
#             axes[0].set_title(f"Distribution of '{col}'")
#             axes[0].set_xlabel(col)
#             axes[0].set_ylabel("Density")
#             # Box Plot (Bottom Subplot)
#             sns.boxplot(data=data, x=col, ax=axes[1])
#             axes[1].set_title(f"Boxplot of '{col}'")
#             axes[1].set_xlabel(col)
#             # Adjust layout and display
#             plt.tight_layout()
#             st.pyplot(fig)
#         st.text("""
# **Number of Columns**:
#    - There are **2 numeric columns** in the dataset: `doors` and `persons`.
# **Shapes Drawn for Each Column**:
#    - For each numeric column, two types of plots are drawn:
#      1. **Distribution Plot (Histogram with KDE)**: This plot shows the distribution of the data along with a Kernel Density Estimate (KDE) to visualize the probability density function.
#      2. **Box Plot**: This plot provides a summary of the data distribution, highlighting the median, quartiles, and potential outliers.
# **Analysis of Distribution and Histogram Shapes**:
#    - **`doors`**:
#      - **Data values**: [`2.0`, `3.0`, `4.0`, `5.0`]
#      - **Distribution Plot**:  The histogram shows the frequency distribution of the number of doors in the dataset. The x-axis represents the number of doors, ranging from 2 to 5, and the y-axis represents the density. The distribution appears to be relatively uniform, with each category (2, 3, 4, and 5 doors) having a similar frequency. This suggests that the dataset contains a balanced number of vehicles with different door counts. The density curve overlaid on the histogram provides a smooth estimate of the distribution, confirming the uniformity.
# 
#      - **Box Plot**: The median value (the line inside the box) is at 3.5, indicating that half of the vehicles have a number of doors less than the value 3.5. The box represents the IQR, which is the range between the 25th percentile (Q1) and the 75th percentile (Q3). For the `doors` variable, Q1 is at 2.75 and Q3 is at 4.25. The whiskers extend to the minimum and maximum values within 1.5 times the IQR from the quartiles. In this case, the whiskers extend from 2 to 5, indicating that these are the minimum and maximum values without any outliers. There are no outliers in the `doors` variable, as all data points fall within the whiskers.
# 
#      - **Overall**: The values of `doors` are distributed uniformly and according to the histogram and the box plot does not display any outliers. Therefore, there are no irregularities in the graph.
# 
#    - **`persons`**:
#      - **Data values**: [`2.0`, `4.0`, `5.0`]
#      - **Distribution Plot**: The histogram shows the frequency distribution of the number of persons that the car can carry in the dataset. The x-axis represents the number of persons, ranging from 2 to 5, and the y-axis represents the density. As opposed to the door's data set, the distribution appears seem to be not uniform, there is not data in the category 3. This causes the data displayed on the bar chart to be spaced far apart. The KDE line shows a data shortage at position value 3.0.
# 
#      - **Box Plot**: The median value (the line inside the box) is at 4.0, indicating that more than half of the vehicles can accommodate 4.0 or fewer persons. The box represents the IQR, which is the range between the 25th percentile (Q1) and the 75th percentile (Q3). For the `doors` variable, Q1 is at 2.75 and Q3 is at 4.25. The whiskers extend to the minimum and maximum values within 1.5 times the IQR from the quartiles. In this case, the whiskers extend from 2 to 5 (3.0 times the IQR from the quartiles), indicating that these are the minimum and maximum values without any outliers. There are no outliers in the `persons` variable, as all data points fall within the whiskers.
#      - **Overall**: The values of `persons` are not distributed uniformly because of the shortage of data value as shown in the distribution plot and the boxplot. However, similar to the situation `doors`, there are no outliers in the data.
# """)
# 
#         st.header("""Plotting Horizontal Bar Plots for Categorical Columns""")
# 
#         # Plotting Horizontal Bar Plots for Categorical Columns
#         for col in categorical_data:
#             fig, ax = plt.subplots(figsize=(8, 5))  # Adjust figsize as needed
#             # Calculate value counts
#             value_counts = data[col].value_counts()
#             # Create the horizontal bar plot
#             ax = sns.barplot(x=value_counts.values, y=value_counts.index, orient='h')
#             # Enhance plot appearance
#             ax.set_xlabel("Count")
#             ax.set_ylabel(col)
#             plt.grid(axis='x', alpha=0.75)  # Add vertical grid
#             # Add count annotations
#             for index, value in enumerate(value_counts.values):
#                 ax.text(value, index, f'{value}', ha='left', va='center')
#             # Display the plot
#             plt.tight_layout()
#             st.pyplot(fig)
#         st.text("""
# **Number of Columns**:
#    - There are **5 categorical values** in the dataset: `buying`, `maint`, `lug_boot`, `safety`, `class`.
# **Shapes Drawn for Each Column**:
#    - For each categorical column, there is a **Distribution Plot** are drawn, which shows the distribution of the data.
# **Analysis of Distribution and Histogram Shapes**:
#    - **`buying`, `maint`**:
#      - **Distribution Plot**: There are 4 columns in the histogram for `buying` and `maint` shows the frequency of unique values (`vhigh`, `high`, `med`, `low`).
#      -  In `buying` and `maint`, the values ​​are distributed almost evenly (the frequent of each unique values is around `432`). There are no abnormalities in the graphs.
#    - **`lug_boot`**:
#      - **Distribution Plot**: There are 3 columns in the histogram for `lug_boot` shows the frequency of unique values (`small`, `med`, `big`).
#      -  In `lug_boot`, the values ​​are distributed almost evenly (the frequent of each unique values is around `576`). There are no abnormalities in the graphs.
#    - **`safety`**:
#      - **Distribution Plot**: There are 3 columns in the histogram for `safety` shows the frequency of unique values (`low`, `med`, `high`).
#      -  In `safety`, the values ​​are distributed almost evenly (the frequent of each unique values is around `576`). There are no abnormalities in the graphs.
#    - **`class`**:
#      - **Distribution Plot**: There are 4 columns in the histogram for `class` shows the frequency of unique values (`unacc`, `acc`, `good`, `vgood`).
#      -  In `class`, the values ​​are distributed unevenly (the frequent `unacc` is count for `1210` out of `1728`). This implies that the majority of the cars in the sample are viewed as unsatisfactory.
# **Overall**
#    - In general, except for the uneven distribution of `class` data, the remaining categorical data in this dataset is evenly distributed. In addition, no abnormalities were detected in the data.
# """)
# 
#         # Calculate and Plot the Correlation Matrix Heatmap
#         st.header("Correlation Matrix")
#         corr_matrix = data[numeric_data].corr()
#         fig, ax = plt.subplots(figsize=(8, 6))
#         sns.heatmap(corr_matrix, cmap='coolwarm', cbar=True, square=True, linewidths=.5, ax=ax)
#         ax.set_title('Heatmap of Correlation Matrix')
#         st.pyplot(fig)
#         st.text("""
# Purpose of the Heatmap:
# - The heatmap visualizes the correlation matrix for five numeric columns: `doors` and `person`. The color scale represents the strength and direction of the correlation between each pair of variables, with red indicating strong positive correlations and blue indicating weaker correlations.
# Analysis of Correlation Patterns:
# - Diagonal Elements: The diagonal elements (top-left and bottom-right) are red, indicating a perfect positive correlation (correlation coefficient of 1.0) between each variable and itself. This is expected as any variable is perfectly correlated with itself.
# - Off-Diagonal Elements: The off-diagonal elements (top-right and bottom-left) are blue, indicating a low or no correlation (correlation coefficient close to 0.0) between the variables `doors` and `persons`. This suggests that there is no linear relationship between the number of doors and the number of persons.
# - Relevance: This heatmap is relevant for understanding the relationships between different variables in a dataset. In this case, it shows that the number of doors and the number of persons are not correlated, which could be useful information for further analysis or decision-making.
# """)
# 
#     except Exception as e:
#         st.error(f"Error loading data: {e}")
# else:
#     st.write("Please enter the Google Drive link of the CSV file.")

!npm install localtunnel

!streamlit run app.py &>/content/logs.txt & npx localtunnel --port 8501 & curl ipv4.icanhazip.com

!streamlit run app.py &>/content/logs.txt & npx localtunnel --port 8501